name: hide_out
description: A Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none'

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.3.2+11

environment:
  sdk: ^3.2.0

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3

  #firebase
  firebase_core: ^2.25.4
  cloud_firestore: ^4.15.5
  firebase_auth: ^4.17.4
  firebase_storage: ^11.6.6
  firebase_analytics: ^10.8.6

  google_sign_in: ^6.2.1

  provider: ^6.0.0

  fluttertoast: ^8.0.7

  uuid: ^3.0.4

  font_awesome_flutter: ^9.1.0

  flutter_sound: ^8.4.2
  permission_handler: ^8.1.2
  path_provider: ^2.0.2
  # needs to be 3.4.1(fix for Android 12) <= x < 3.0.5(breaking change)
  assets_audio_player: <3.0.5
  tuple: ^2.0.0

  flutter_slidable: ^0.6.0

  intro_slider: ^3.0.10

  collection: ^1.15.0-nullsafety.4

  image_picker: ^0.8.4+1
  intl: ^0.17.0
  cached_network_image: ^3.3.1
  sign_in_with_apple: ^5.0.0
  firebase_remote_config: ^4.3.14
  package_info: ^2.0.2
  url_launcher: ^6.1.8
  loading_animation_widget: ^1.1.0+3
  recase: ^4.1.0
  flutter_markdown: ^0.6.10
  url_strategy: ^0.2.0
  tutorial_coach_mark: ^1.2.11
  wakelock: ^0.6.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path_ios: "assets/images/app_icon_ios.png"
  image_path_android: "assets/images/app_icon_android.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/app_icon_android.png"

# prevent transitive dependencies from causing errors
# cf. https://stackoverflow.com/questions/70363918/error-member-not-found-packageroot-how-to-solve-ignore-deprecated-member-u
dependency_overrides:
  platform: ^3.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - assets/images/
     - assets/images/slides/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
